version: "3"

networks:
  default:

services:
### nginx ################################################
 nginx:
   build:
     context: ./services/nginx
     args:
       NGINX_VERSION: nginx:${NGINX_VERSION}
       CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
       NGINX_INSTALL_APPS: ${NGINX_INSTALL_APPS}
   container_name: nginx
   ports:
     - "${NGINX_HTTP_HOST_PORT}:80"
     - "${NGINX_HTTPS_HOST_PORT}:443"
     - 8010:8010
     - 8020:8020
     - 8030:8030
     - 8040:8040
     - 8050:8050
     - 8060:8060
     - 8070:8070
     - 8080:8080
     - 8090:8090
   volumes:
     - ${SOURCE_DIR}:/www/:rw
     - ${NGINX_SSL_CERTIFICATE_DIR}:/ssl:rw
     - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d/:rw
     - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
     - ${NGINX_FASTCGI_PHP_CONF}:/etc/nginx/fastcgi-php.conf:ro
     - ${NGINX_FASTCGI_PARAMS}:/etc/nginx/fastcgi_params:ro
     - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
   environment:
     TZ: "$TZ"
   restart: always
   networks:
     - default

### php ################################################
 php:
   build:
     context: ./services/php
     args:
       PHP_VERSION: php:${PHP_VERSION}-fpm-alpine
       CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
       PHP_EXTENSIONS: ${PHP_EXTENSIONS}
       TZ: "$TZ"
   container_name: php
   expose:
     - 9501
   extra_hosts:
     - "www.site1.com:172.17.0.1"
   volumes:
     - ${SOURCE_DIR}:/www/:rw
     - ${PHP_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
     - ${PHP_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
     - ${PHP_LOG_DIR}:/var/log/php
     - ${DATA_DIR}/composer:/tmp/composer
   restart: always
   cap_add:
     - SYS_PTRACE
   networks:
     - default

### mariadb ################################################

 mysql:
   image: linuxserver/mariadb
   container_name: mysql
   ports:
     - "${MYSQL_HOST_PORT}:3306"
   volumes:
     - ${DATA_DIR}/mariadb:/config/:rw
   restart: always
   networks:
     - default
   environment:
     PUID: 1000
     PGID: 1000
     MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
     TZ: "$TZ"


### Portainer ################################################
 portainer:
   image: portainer/portainer:latest
   container_name: portainer
   volumes:
     - ${DATA_DIR}/portainer_data:/data
     - /var/run/docker.sock:/var/run/docker.sock
   extra_hosts:
     - "dockerhost:${DOCKER_HOST_IP}"
   ports:
     - 9010:9000
   networks:
     - default
   restart: always

